In [1]:
import torch


In [2]:
x = torch.tensor([1, 2, 3], dtype=torch.float32)
x


tensor([1., 2., 3.])

In [3]:
x = torch.tensor([1, 2, 3], dtype=torch.float32, requires_grad=True)
x


tensor([1., 2., 3.], requires_grad=True)

In [4]:
x = torch.tensor([1, 2, 3]).to("cuda")
y = torch.tensor([2, 3, 4]).to("cpu")

x + y

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

# Autodiff


In [6]:
x = torch.tensor([-3.5], requires_grad=True)
print(x.grad)

None


In [20]:
def f(x):
    return torch.pow((x - 2.0), 2)

In [9]:
value = f(x)


In [10]:
value.backward()

In [11]:
print(x.grad)

tensor([-11.])


In [12]:
(2 - 11) ** 2


81

## Minimizando a função


In [17]:
x = torch.tensor([-3.5], requires_grad=True)

x_cur = x.clone()
x_prev = x_cur * 100

epsilon = 1e-5

eta = 0.1

while torch.linalg.norm(x_cur - x_prev) > epsilon:
    x_prev = x_cur.clone()
    value = f(x)
    value.backward()
    x.data -= eta * x.grad
    x.grad.zero_()
    x_cur = x.data

print(x_cur)


tensor([2.0000])


# Optimzing a function with PyTorch


In [35]:
eta = 0.1
x_param = torch.nn.Parameter(torch.tensor([-3.5]), requires_grad=True)
optimizer = torch.optim.SGD([x_param], lr=eta)

for epoch in range(200):
    optimizer.zero_grad()
    loss_incurred = f(x_param)
    loss_incurred.backward()
    optimizer.step()

print(x_param.data)

tensor([2.0000])


In [36]:
x_param


Parameter containing:
tensor([2.0000], requires_grad=True)